In [ ]:
import numpy as np

a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
import time

a= np.random.rand(1000000)
b= np.random.rand(1000000)

m = np.array([a,b])
print(m)

tic = time.time()
c= np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(1000000):
  c+=a[i]*b[i]
toc = time.time()
print(c)
print("for loop " + str(1000*(toc-tic)) + "ms")

[[0.66397837 0.939299   0.7317437  ... 0.41829233 0.53160304 0.61755432]
 [0.23757719 0.02435407 0.45474896 ... 0.39899786 0.35749941 0.83764846]]
250046.78408481367
Vectorized version: 2.659320831298828ms
250046.78408481457
for loop 696.1674690246582ms
